import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import {
  SRIJIKA_OWNER_FILE_CONTRACT,
  SRIJIKA_SHARED_FILE_CONTRACT,
  SRIJIKA_STRUCTURE_CREATION_MATRIX,
} from '@srijika/architecture-rules/creation';
import {
  CAPABILITIES,
  DOCUMENT_FORMAT_VERSION,
  PROTOCOL_VERSION,
  SRIJIKA_RPC_METHODS,
  SRIJIKA_TOOL_NAMES,
  TOOL_VERSION,
} from '@srijika/automation-protocol';
import {
  SRIJIKA_REACT_MIGRATION_TOOL_LIST,
  SRIJIKA_REACT_MIGRATION_TOOL_NAMES,
} from './react-migration-contract';

interface DocumentationResource {
  uri: string;
  title: string;
  description: string;
  value: Record<string, unknown>;
}

export const SRIJIKA_DOCUMENTATION: readonly DocumentationResource[] = [
  {
    uri: 'srijika://docs/protocol',
    title: 'Srijika automation protocol',
    description: 'Versioned tool, RPC, capability, and compatibility contract.',
    value: {
      schemaVersion: 1,
      protocolVersion: PROTOCOL_VERSION,
      toolVersion: TOOL_VERSION,
      documentFormatVersion: DOCUMENT_FORMAT_VERSION,
      capabilities: CAPABILITIES,
      rpcMethods: SRIJIKA_RPC_METHODS,
      toolNames: SRIJIKA_TOOL_NAMES,
      writeContract: {
        atomic: true,
        requiresExpectedRevision: true,
        onConflict: 'refetch-rebase-retry-once',
        validatesBeforeCommit: true,
      },
    },
  },
  {
    uri: 'srijika://docs/document-model',
    title: 'Srijika document model',
    description: 'Compact canonical AST model used by Studio, renderers, codegen, and tools.',
    value: {
      schemaVersion: 1,
      documentFormatVersion: DOCUMENT_FORMAT_VERSION,
      topLevelFields: [
        'formatVersion',
        'id',
        'kind',
        'name',
        'rootNodeId',
        'revision',
        'nodes',
        'symbols',
        'publicProps',
      ],
      nodeKinds: ['element', 'text', 'expression', 'fragment', 'if', 'repeat', 'slot'],
      expressionKinds: [
        'literal',
        'reference',
        'unary',
        'binary',
        'conditional',
        'template',
        'customCodeReference',
      ],
      invariants: [
        'one locked page root',
        'one parent per non-root node',
        'acyclic and fully reachable graph',
        'registered component ports or approved instance ports',
        'typed visible symbol references',
        'logic enters UI through declared props and events',
      ],
    },
  },
  {
    uri: 'srijika://docs/design-plan',
    title: 'Srijika design plan contract',
    description: 'How Codex converts a visible design into a compact atomic operation plan.',
    value: {
      schemaVersion: 1,
      canonicalTool: SRIJIKA_TOOL_NAMES.importDesignPlan,
      imageHandling:
        'Codex analyzes the supplied image; the local bridge receives structured JSON operations only.',
      planFields: [
        'pageId',
        'expectedRevision',
        'planId',
        'phase',
        'source',
        'requiredRegions',
        'acceptance',
        'assumptions',
        'operations',
      ],
      phases: ['geometry', 'content', 'styling', 'correction', 'final'],
      metadataContract:
        'requiredRegions and acceptance are echoed caller-enforced metadata; verify them with layout and capture reads.',
      operationContract:
        'Components, public props, events, Repeat/If structure, and responsive breakpoint styles belong inside operations.',
      verification: [
        'validate document',
        'read diagnostics',
        'render exact source viewport',
        'inspect computed layout and overflow',
        'capture clean PNG',
        'compare and correct largest mismatch',
      ],
    },
  },
  {
    uri: 'srijika://docs/code-first-architecture',
    title: 'Srijika code-first architecture',
    description:
      'Machine-readable Feature, Slot, Part, and strict Shared ownership and progressive behavior-chain contract.',
    value: {
      schemaVersion: 1,
      contractId: 'srijika.progressive-behavior-chain',
      ownerKinds: ['feature', 'slot', 'part', 'shared-ui', 'shared-widget', 'shared-capability'],
      ownerContract: {
        required: SRIJIKA_OWNER_FILE_CONTRACT.required,
        optional: SRIJIKA_OWNER_FILE_CONTRACT.optional,
        canonicalFiles: {
          ui: '{Owner}{uiSuffix}',
          connector: '{Owner}{connectorSuffix}',
          hook: 'use{Owner}.ts OR {hooksDirectory}/use{Owner}.ts (mutually exclusive)',
          store:
            '{owner}{storeSuffix} OR {storesDirectory}/{owner}{storeSuffix} (mutually exclusive)',
          logic: '{owner}{logicSuffix}',
          api: '{owner}{apiSuffix}',
          types: '{owner}{typesSuffix}',
        },
        progressiveLayouts: {
          hook: 'Start flat. Adding {hooksDirectory}/use{Owner}{Behavior}.ts atomically moves the gateway to {hooksDirectory}/use{Owner}.ts, rewires imports, and removes the root gateway.',
          store:
            'Start flat. Adding {storesDirectory}/{owner}{Concern}{storeSuffix} atomically moves the gateway to {storesDirectory}/{owner}{storeSuffix}, rewires imports, and removes the root gateway.',
          exclusivity:
            'Flat and expanded gateways cannot coexist. {hooksDirectory}/ and {storesDirectory}/ are one level deep and do not use index.ts.',
          migrationScope:
            'Rewire the complete bounded project TS/JS source tree, not only ownership roots; exclude declarations and ignored generated/vendor directories and stop at nested Srijika project boundaries.',
          migrationAtomicity:
            'Unsafe entries, symlinks, incomplete scans, stale sources, and count/byte-limit failures abort before mkdir, move, create, or update.',
        },
        privateHelperHooks:
          'Only {hooksDirectory}/use{Owner}{Behavior}.ts is valid; consumers enter through {hooksDirectory}/use{Owner}.ts.',
        privateStoreSlices:
          'Only {storesDirectory}/{owner}{Concern}{storeSuffix} is valid; consumers enter through {storesDirectory}/{owner}{storeSuffix}.',
        uiBoundary: {
          renderedOnlyByMatchingConnector: true,
          externalRuntimeBehaviorAllowed: false,
          allowedExternalImports: [
            'type-only imports',
            'styles and assets',
            'safe React JSX support',
            'presentational bindings used exclusively as JSX tags',
          ],
          presentationalAssetExtensions: [
            'css',
            'scss',
            'sass',
            'less',
            'styl',
            'svg',
            'png',
            'jpg',
            'jpeg',
            'gif',
            'webp',
            'avif',
            'ico',
            'woff',
            'woff2',
            'ttf',
            'otf',
            'eot',
            'mp3',
            'wav',
            'ogg',
            'mp4',
            'webm',
          ],
          directChildUiDiagnostic: {
            code: 'SRIJIKA4116',
            ruleId: 'SRIJIKA-ARCH-DIRECT-CHILD-UI',
          },
          behaviorDiagnostic: {
            code: 'SRIJIKA4101',
            ruleId: 'SRIJIKA-ARCH-UI-RUNTIME-IMPORT',
          },
          crossOwnerException:
            'A pure UI may compose only the canonical public UI boundary of a Shared UI Primitive.',
          dataAndBehaviorEntry: 'typed props, event callbacks, and ReactNode composition props',
          forbiddenBehavior: {
            hookCalls:
              'identifier and property-access Hooks, including useOwner() and React.useState()',
            browserRuntimeApis: [
              'fetch',
              'XMLHttpRequest',
              'WebSocket',
              'EventSource',
              'Worker',
              'SharedWorker',
              'BroadcastChannel',
              'localStorage',
              'sessionStorage',
              'indexedDB',
              'caches',
              'document',
              'navigator',
              'location',
              'history',
              'Notification',
              'timers',
              'animation/idle callbacks',
              'DOM observers',
              'Image',
              'Audio',
              'FileReader',
              'DOMParser',
              'performance',
              'screen',
              'window',
              'globalThis',
              'self',
              'process',
              'Deno',
              'Bun',
            ],
            runtimeLayers: ['connector', 'hook', 'store', 'logic', 'api'],
            externalRuntimeBehavior:
              'hooks, state, routing, requests, query lifecycle, browser APIs, and callable utilities',
          },
        },
        logicBoundary: {
          frameworkFree: true,
          deterministic: true,
          allowed: [
            'business rules',
            'pure validation and authorization decisions',
            'deterministic transforms and aggregation',
            'multi-step orchestration through the matching API boundary',
            'passive Types and pure utility modules',
          ],
          forbiddenRuntimeConcerns: [
            'React and React Hooks',
            'React Query and query-cache lifecycle',
            'router lifecycle and navigation state',
            'client-state libraries and state lifecycle',
            'browser globals and request transport',
          ],
          forbiddenTransportApis: [
            'fetch',
            'fetch.call',
            'XMLHttpRequest',
            'WebSocket',
            'EventSource',
            'Request',
          ],
          forbiddenTransportModules: [
            'node:http',
            'node:https',
            'http',
            'https',
            'undici',
            'cross-fetch',
            'node-fetch',
            'ofetch',
          ],
          lifecycleOwners: {
            reactAndQuery: 'hook',
            sharedClientState: 'store',
            routing: 'connector',
            requestTransport: 'api',
          },
          diagnostic: {
            code: 'SRIJIKA4118',
            ruleId: 'SRIJIKA-ARCH-LOGIC-RUNTIME-CONCERN',
          },
        },
        passiveTypes: {
          runtimeStep: false,
          allowedDeclarations: [
            'interface',
            'type-alias',
            'import-type',
            'export-type',
            'export {}',
          ],
          runtimeDeclarationsAllowed: false,
          runtimeValueReferencesAllowed: false,
          consumption: 'import type/export type only',
          diagnostic: {
            code: 'SRIJIKA4117',
            ruleId: 'SRIJIKA-ARCH-PASSIVE-TYPES',
          },
        },
      },
      sharedOwnerContract: {
        root: '{sharedRoot}',
        arbitraryFoldersAllowed: false,
        importsFeatures: false,
        consumersUsePublicBoundaryOnly: true,
        kinds: {
          'shared-ui': {
            directory: '{sharedRoot}/ui/{owner-folder}',
            label: 'Shared UI Primitive',
            required: SRIJIKA_SHARED_FILE_CONTRACT.ui.required,
            optional: SRIJIKA_SHARED_FILE_CONTRACT.ui.optional,
            forbidden: ['connector', 'hook', 'store', 'logic', 'api'],
            publicBoundary: 'ui',
            rule: 'All data, events, and composition enter through typed props.',
          },
          'shared-widget': {
            directory: '{sharedRoot}/widgets/{owner-folder}',
            label: 'Shared Widget',
            required: SRIJIKA_SHARED_FILE_CONTRACT.widget.required,
            optional: SRIJIKA_SHARED_FILE_CONTRACT.widget.optional,
            forbidden: [],
            publicBoundary: 'connector',
            expandedGateways: [
              '{hooksDirectory}/use{Owner}.ts',
              '{storesDirectory}/{owner}{storeSuffix}',
            ],
          },
          'shared-capability': {
            directory: '{sharedRoot}/capabilities/{owner-folder}',
            label: 'Shared Headless Capability',
            required: ['at-least-one-runtime-layer'],
            optional: SRIJIKA_SHARED_FILE_CONTRACT.capability.optional,
            forbidden: ['ui', 'connector'],
            runtimeMinimum: SRIJIKA_SHARED_FILE_CONTRACT.capability.minimumRuntimeCapabilities,
            typesAloneAllowed: false,
            publicBoundary: 'hook-otherwise-store-otherwise-logic-otherwise-api',
            expandedGateways: [
              '{hooksDirectory}/use{Owner}.ts',
              '{storesDirectory}/{owner}{storeSuffix}',
            ],
          },
        },
        examples: {
          button: 'shared-ui',
          userMenu: 'shared-widget',
          authSession: 'shared-capability',
          commonHttpBoundary: 'shared-capability',
        },
      },
      creation: {
        contractVersion: 1,
        triggers: [
          'studio-folder-plus',
          'studio-folder-context-menu',
          'vscode-explorer-context',
          'cli-add',
          'mcp-plan-apply',
        ],
        expansionCommands: {
          hook: 'srijika add behavior-hook <Behavior> --in <owner>',
          store: 'srijika add store-slice <Concern> --in <owner>',
        },
        sharedCommands: {
          ui: 'srijika add shared-ui <Name> [--types]',
          widget: 'srijika add shared-widget <Name> [--hook --store --logic --api --types]',
          capability:
            'srijika add shared-capability <Name> <--hook|--store|--logic|--api> [capability flags]',
        },
        ownerActions: SRIJIKA_STRUCTURE_CREATION_MATRIX,
        compositeOwners: {
          feature: {
            parent: '{featuresRoot}',
            required: SRIJIKA_OWNER_FILE_CONTRACT.required,
            selectable: SRIJIKA_OWNER_FILE_CONTRACT.optional,
          },
          slot: {
            parent: 'feature-root',
            required: SRIJIKA_OWNER_FILE_CONTRACT.required,
            selectable: SRIJIKA_OWNER_FILE_CONTRACT.optional,
          },
          part: {
            parent: 'slot-root',
            required: SRIJIKA_OWNER_FILE_CONTRACT.required,
            selectable: SRIJIKA_OWNER_FILE_CONTRACT.optional,
          },
          sharedUi: {
            parent: '{sharedRoot}/ui',
            required: SRIJIKA_SHARED_FILE_CONTRACT.ui.required,
            selectable: SRIJIKA_SHARED_FILE_CONTRACT.ui.optional,
          },
          sharedWidget: {
            parent: '{sharedRoot}/widgets',
            required: SRIJIKA_SHARED_FILE_CONTRACT.widget.required,
            selectable: SRIJIKA_SHARED_FILE_CONTRACT.widget.optional,
          },
          sharedCapability: {
            parent: '{sharedRoot}/capabilities',
            required: ['at-least-one-runtime-layer'],
            selectable: SRIJIKA_SHARED_FILE_CONTRACT.capability.optional,
          },
        },
        naming: {
          owner: 'normalized PascalCase',
          folder: 'derived kebab-case',
          alternateNamesAllowed: false,
        },
        writePolicy: {
          preflightAllPaths: true,
          overwrite: false,
          coherentBatch: true,
          arbitraryFolders: false,
        },
      },
      architectureConfiguration: {
        file: 'srijika.config.json',
        projectContract: {
          sourceOfTruth: {
            required: true,
            exactValue: 'tsx',
          },
          entry: {
            required: true,
            projectRelative: true,
            maximumSegments: 32,
            mustEndWithResolvedUiSuffix: true,
          },
          architecture: {
            required: false,
            overrideFieldCount: 12,
            omittedOverrideBehavior: 'canonical default',
          },
        },
        profilePolicy: {
          supported: 'feature-slot-part-v1',
          architectureBlockAbsent: 'use canonical defaults',
          architectureBlockPresent: 'profile is required and must exactly match supported',
          missingProfile: 'fail closed',
          unsupportedProfile: 'fail closed',
          surfaces: ['generated validator', 'CLI', 'VS Code', 'Studio', 'MCP'],
        },
        supportedOverrides: {
          roots: ['featuresRoot', 'sharedRoot'],
          directories: ['slotsDirectory', 'partsDirectory', 'hooksDirectory', 'storesDirectory'],
          suffixes: [
            'uiSuffix',
            'connectorSuffix',
            'storeSuffix',
            'logicSuffix',
            'apiSuffix',
            'typesSuffix',
          ],
        },
        brownfieldAdoption: {
          version: 1,
          profile: 'brownfield-ownership-v1',
          managedRoots: 'bounded project-relative discovery roots',
          include: 'bounded paths requiring coverage',
          excludeCategories: ['server', 'service', 'domain', 'test'],
          adoptedOwners: 'non-overlapping owner roots under include',
          recognizedDirectories: ['ui', 'connectors', 'hooks'],
          coverage: ['governed', 'pending', 'blocked', 'excluded'],
          fullProjectSuccess: 'true only when every covered file is governed',
          planner: 'read-only deterministic moves and exact static import rewires',
          strictScope: 'adopted owners plus authoritative entry',
        },
        safety: {
          rootMaximumSegments: 10,
          rootsProjectRelative: true,
          rootsNonOverlapping: true,
          directoryNamesSingleSegment: true,
          directoryNamesDistinct: true,
          suffixesBasenameOnly: true,
          suffixesDistinct: true,
          suffixComparison: 'case-insensitive',
          suffixesMayEndWithAnotherConfiguredSuffix: false,
          uiAndConnectorSuffixExtension: '.tsx',
          runtimeSuffixExtension: '.ts',
          declarationSuffixesAllowed: false,
          traversalAllowed: false,
          absolutePathsAllowed: false,
          backslashesAllowed: false,
          symlinkEscapesAllowed: false,
          filesystemBoundary:
            'Project readers and structure writers reject symlinked roots, configs, source files, and scope ancestors before reading or writing.',
        },
        readBudgets: {
          projectConfigBytes: 64 * 1024,
          typescriptConfigBytes: 1024 * 1024,
          architectureAndMigrationCorpus: {
            maximumSourceFiles: 4096,
            maximumEntries: 32768,
            maximumDirectories: 4096,
            maximumDepth: 32,
            maximumBytesPerSource: 4 * 1024 * 1024,
            maximumTotalSourceBytes: 24 * 1024 * 1024,
            incompleteCorpusBehavior: 'fail closed; never return a partial validation or rewire',
            authoritativeEntry:
              'Always included in validation and the source-file count even outside Feature/Shared roots; remains a strict UI and receives SRIJIKA4119-SRIJIKA4121 checks.',
          },
        },
        typescriptAliases: {
          file: 'tsconfig.json',
          syntax: 'JSONC',
          extends: 'rejected',
          references: 'absent or empty array only; nonempty project references are rejected',
          baseUrl: 'optional bounded project-relative base for path targets',
          source: 'compilerOptions.paths',
          acceptedPatterns: ['exact', 'slash-delimited terminal /* wildcard'],
          targetPolicy: 'first target is authoritative and must remain inside the project',
          generatedAliases: ['@/', '@features/', '@shared/'],
          reservedLocalNamespaces: ['~/', '#...', '@app', '@src'],
          viteOnlyAliasesSupported: false,
          viteAliasRequirement:
            'Declare the same mapping in tsconfig.json; Vite configuration is not a second architecture source.',
          externalPackages: 'ordinary npm package specifiers remain external',
        },
        runtimeParity: {
          generatedValidator: {
            file: 'scripts/srijika-validate.mjs',
            readsCurrentProjectConfigAtRuntime: true,
            retainsGeneratedArchitectureSnapshot: false,
            effect:
              'Valid root, directory, and suffix changes take effect without regenerating the script.',
          },
          cliWatch: {
            command: 'srijika check --watch',
            implementation: 'one recursive project-root watcher with filtered events',
            watches: [
              'srijika.config.json',
              'root tsconfig.json',
              'configured entry',
              'resolved featuresRoot and sharedRoot',
              'ancestors where a future configured root may appear',
            ],
            filters:
              'Generated/vendor directories are ignored during normal and recovery operation.',
            reloadsProjectConfigBeforeEachCheck: true,
            invalidConfigurationRecovery:
              'Stay alive, watch all non-ignored project paths until configuration is valid, then resume resolved-path filtering.',
            hardcodedSrcWatch: false,
          },
          exactFilePreviews: {
            surfaces: ['VS Code', 'Studio'],
            source: 'canonical ownership planner with resolved project architecture',
            hardcodedPaths: false,
            covers: [
              'created files',
              'safe moves',
              'safe rewires',
              'custom directories',
              'custom suffixes',
            ],
          },
          studioLivePreview: {
            initialSource: 'configured entry',
            sourceDiscovery: 'configured uiSuffix under configured Feature and Shared roots',
            connectorResolution: 'configured connectorSuffix',
            legacyBridgePolicy:
              'upgrade only a recognizable generated bridge; preserve application-owned custom bridges',
          },
        },
      },
      capabilityOrder: ['connector', 'hook', 'store', 'logic', 'api'],
      resolution: {
        connector: ['hook', 'store', 'logic', 'api'],
        hook: ['store', 'logic', 'api'],
        store: ['logic', 'api'],
        logic: ['api'],
        api: ['sharedHttp', 'backend'],
      },
      rules: {
        highestAvailable:
          'Call the first capability present in the ordered resolution list for the same owner and behavior.',
        noJump: 'Never skip an available intermediate capability for the same owner and behavior.',
        returnPath: 'Return results through the same chain and map them to typed UI props.',
        uiIsolation:
          'Only the matching Connector renders an owner UI. Every UI renderer, including a configured entry outside ownership roots, is behavior-free: no Hook invocation (identifier or property access), browser/runtime API access, runtime-layer import, request, state, effect, or business logic; data and events enter through typed props.',
        uiPropsContract:
          'UI accepts one named props parameter. Its named interface is local or resolved from that same owner passive Types file through a relative import type; destructuring, runtime imports, unresolved contracts, and cross-owner contract imports fail.',
        composition:
          'Feature Connectors compose Slot Connectors; Slot Connectors compose Part Connectors. Parent and sibling owners never import child UI directly. The only cross-owner UI exception is pure UI composition of a canonical Shared UI Primitive.',
        passiveTypes:
          'Types files contain passive interfaces and type aliases only. They use import type/export type, expose no runtime declaration, and reference no runtime value such as typeof or a computed value expression.',
        sharedDirection:
          'Shared never imports Features. Consumers use only the public boundary of a Shared UI Primitive, Shared Widget, or Shared Headless Capability. Runtime dependencies between Shared owners must remain acyclic; type-only edges do not create runtime cycles.',
        noFreehandShared:
          'Only {sharedRoot}/ui, {sharedRoot}/widgets, and {sharedRoot}/capabilities contain normalized shared owners; utilities, common folders, barrels, alternate names, and deeper folders are invalid.',
        canonicalNaming:
          'Feature, Slot, Part, and Shared owner folders use exact derived kebab-case; owner files use the matching derived PascalCase/camelCase names. Alternate spellings are hard errors.',
        logicIsolation:
          'Logic remains framework-free and deterministic: pure validation, authorization, transforms, aggregation, and API orchestration are allowed; React, query lifecycle, router lifecycle, and client-state lifecycle move to Hook, Connector, or Store.',
        nextFrameworkAdapter:
          'Versioned adapter srijika.next-app-router v1 recognizes only exact registered source imports. Built-in next/link and next/image plus explicitly configured project-local pure presentation components compile to bounded core preview nodes without loading or executing their modules. App Router pages and layouts are server components unless their directive prologue contains use client; route handlers remain server-owned code.',
      },
      promotion: [
        { when: 'one Part needs it', to: 'part-root' },
        { when: 'two sibling Parts need it', to: 'slot-root' },
        { when: 'two sibling Slots need it', to: 'feature-root' },
        { when: 'two Features need it', to: '{sharedRoot}' },
      ],
      cacheAndState: {
        hook: [
          'React lifecycle',
          'optional TanStack Query',
          'server cache',
          'retry',
          'refetch',
          'mutations',
          'effects',
        ],
        store: ['shared client state', 'selectors', 'synchronous transitions', 'owner actions'],
        invariant: 'Do not mirror one server entity in both Query cache and Zustand.',
        reactQuery: {
          default: false,
          createFlag: '--react-query',
          generates: ['@tanstack/react-query dependency', 'QueryClient', 'AppProviders wrapper'],
        },
      },
      diagnostics: {
        numericCodes: {
          uiRuntimeImport: 'SRIJIKA4101',
          directChildUi: 'SRIJIKA4116',
          passiveTypes: 'SRIJIKA4117',
          logicRuntimeConcern: 'SRIJIKA4118',
          unprovableDynamicImport: 'SRIJIKA4119',
          unresolvedProjectAlias: 'SRIJIKA4120',
          unresolvedProjectImport: 'SRIJIKA4121',
          recommendation: 'SRIJIKA4202',
          unsupportedFrameworkPrimitive: 'SRIJIKA5001',
          unprovableFrameworkUsage: 'SRIJIKA5002',
          invalidFrameworkProps: 'SRIJIKA5003',
          serverClientBoundary: 'SRIJIKA5004',
          nonSerializableBoundaryProp: 'SRIJIKA5005',
        },
        errors: [
          'SRIJIKA-ARCH-MISSING-UI',
          'SRIJIKA-ARCH-MISSING-CONNECTOR',
          'SRIJIKA-ARCH-LAYER-JUMP',
          'SRIJIKA-ARCH-UI-RUNTIME-IMPORT',
          'SRIJIKA-ARCH-PRIVATE-IMPORT',
          'SRIJIKA-ARCH-DIRECT-CHILD-UI',
          'SRIJIKA-ARCH-REVERSE-DEPENDENCY',
          'SRIJIKA-ARCH-STRICT-OWNER-SHAPE',
          'SRIJIKA-ARCH-MIXED-CAPABILITY-LAYOUT',
          'SRIJIKA-ARCH-MISSING-CAPABILITY-GATEWAY',
          'SRIJIKA-ARCH-SHARED-REVERSE-DEPENDENCY',
          'SRIJIKA-ARCH-SHARED-PRIVATE-IMPORT',
          'SRIJIKA-ARCH-SHARED-MISSING-RUNTIME-GATEWAY',
          'SRIJIKA-ARCH-PASSIVE-TYPES',
          'SRIJIKA-ARCH-LOGIC-RUNTIME-CONCERN',
          'SRIJIKA-ARCH-UNPROVABLE-DYNAMIC-IMPORT',
          'SRIJIKA-ARCH-UNRESOLVED-PROJECT-ALIAS',
          'SRIJIKA-ARCH-UNRESOLVED-PROJECT-IMPORT',
        ],
        recommendations: {
          deterministicVersion: 1,
          blocking: false,
          sizeScope:
            'UI thresholds are per owner and do not limit total Features, Slots, Parts, Shared owners, or application size.',
          entries: [
            {
              code: 'SRIJIKA-ARCH-RECOMMEND-LOGIC',
              trigger:
                'two or more endpoint calls, business branching, validation, authorization, transformation, aggregation, or multi-step orchestration',
            },
            {
              code: 'SRIJIKA-ARCH-RECOMMEND-HOOK',
              trigger:
                'cache/retry/polling/cancellation/subscription/pagination/mutation lifecycle, two or more async handlers, or three or more React lifecycle hooks',
            },
            {
              code: 'SRIJIKA-ARCH-RECOMMEND-STORE',
              trigger:
                'state used by two or more descendants, props cross two ownership boundaries, or four or more related local state fields',
            },
            {
              code: 'SRIJIKA-ARCH-RECOMMEND-HOOK-ABOVE-STORE',
              trigger:
                'five or more Store selectors/actions consumed by a Connector, or Store actions own async lifecycle/cache responsibilities',
            },
            {
              code: 'SRIJIKA-ARCH-RECOMMEND-PROMOTE-OWNER',
              trigger:
                'a private Hook, Store, Logic, or API is consumed across an owner boundary, proving two owner consumers and requiring the nearest common owner',
              emission:
                'returned in recommendations and attached to the blocking private-ownership diagnostic with evidence owner-consumers=2',
            },
            {
              code: 'SRIJIKA-ARCH-RECOMMEND-SPLIT-OWNER',
              trigger:
                'UI function exceeds 200 meaningful lines, UI file exceeds 300, or public contract exceeds 16 top-level members',
              emission:
                'returned in recommendations and emitted as non-blocking SRIJIKA4202 only when a threshold is strictly exceeded',
            },
          ],
        },
      },
    },
  },
  {
    uri: 'srijika://docs/react-migration',
    title: 'Srijika React migration',
    description:
      'Machine-readable immutable-source, distinct-target, reviewed-slice migration contract.',
    value: {
      schemaVersion: 2,
      contractId: 'srijika.react-migration-native-v2',
      sessionFile: '.srijika/migrations/react/session.json',
      adapters: ['cli', 'codex-mcp', 'vscode', 'desktop'],
      frameworkAdapters: {
        react: ['vite', 'create-react-app'],
        next: {
          id: 'next-app-router',
          appRoots: ['app', 'src/app'],
          exactFrameworkPaths: true,
          protectedServerFilesMayEnterUiOwners: false,
          productionBuild: 'next build',
          parityRuntime: 'next dev',
        },
      },
      sourceContract: {
        immutable: true,
        baselineRequired: true,
        finalBaselineMatchRequired: true,
        sourceAndTargetMustBeDistinct: true,
        nestedOrOverlappingRootsAllowed: false,
        symlinkAliasesAllowed: false,
      },
      targetContract: {
        newOrRecognizableCleanStarterTarget: true,
        atomicSliceWrites: true,
        writesOutsideTargetAllowed: false,
        unrelatedOverwriteAllowed: false,
      },
      responsibility: {
        engine: [
          'canonical-path-safety',
          'source-baseline',
          'bounded-inventory',
          'source-import-and-ownership-graph',
          'deterministic-owner-role-plan',
          'byte-bounded-immutable-slice-context',
          'persisted-plan-and-session',
          'persisted-reviewed-slice-payload',
          'review-token-bound-to-source-target-plan-and-payload',
          'atomic-target-writes',
          'source-to-target-traceability',
          'native-completion-and-closed-target-graph',
          'wrapper-and-runtime-fallback-rejection',
          'fail-closed-verification',
        ],
        codex: [
          'semantic-source-analysis',
          'semantic-route-discovery-beyond-filename-classification',
          'implement-deterministic-owner-plan',
          'reviewed-slice-implementation',
          'blocker-and-assumption-reporting',
        ],
      },
      sessionPhases: ['planned', 'scaffolded', 'migrating', 'verifying', 'blocked', 'complete'],
      workflowStages: [
        'preflight',
        'baseline',
        'inventory',
        'ownership-plan',
        'scaffold',
        'slice-review',
        'slice-migration',
        'slice-verification',
        'global-verification',
        'finalized',
      ],
      inventory: [
        'toolchain-and-entry',
        'routes-and-layouts',
        'components-props-and-events',
        'hooks-context-state-and-query',
        'api-auth-and-browser-boundaries',
        'styles-assets-and-responsive-behavior',
        'forms-environment-loading-and-errors',
        'unit-integration-end-to-end-and-visual-tests',
      ],
      tools: SRIJIKA_REACT_MIGRATION_TOOL_LIST,
      toolFlow: {
        create: SRIJIKA_REACT_MIGRATION_TOOL_NAMES.create,
        scan: SRIJIKA_REACT_MIGRATION_TOOL_NAMES.scanSource,
        plan: SRIJIKA_REACT_MIGRATION_TOOL_NAMES.getPlan,
        reviewOwnership: SRIJIKA_REACT_MIGRATION_TOOL_NAMES.reviewOwnership,
        sliceContext: SRIJIKA_REACT_MIGRATION_TOOL_NAMES.getSliceContext,
        reviewNativeSlice: SRIJIKA_REACT_MIGRATION_TOOL_NAMES.reviewSlice,
        applyReviewedSlice: SRIJIKA_REACT_MIGRATION_TOOL_NAMES.applySlice,
        verifySlice: SRIJIKA_REACT_MIGRATION_TOOL_NAMES.verifySlice,
        resume: SRIJIKA_REACT_MIGRATION_TOOL_NAMES.getStatus,
        verifySession: SRIJIKA_REACT_MIGRATION_TOOL_NAMES.verify,
        finalize: SRIJIKA_REACT_MIGRATION_TOOL_NAMES.finalize,
      },
      completionEvidence: [
        'source-unchanged',
        'complete-source-to-target-traceability',
        'all-runtime-mappings-native',
        'deterministic-owner-and-role-obligations-satisfied',
        'no-wrapper-or-runtime-fallback-findings',
        'closed-target-import-and-dependency-graph',
        'no-unowned-target-source-modules',
        'zero-srijika-diagnostics',
        'strict-srijika-architecture',
        'build',
        'typecheck',
        'tests',
        'route-equivalence-when-applicable',
        'responsive-visual-evidence-when-applicable',
      ],
      verificationEvidence: {
        commandExecution: {
          executedBy: 'srijika-engine',
          callerAuthoredStatusAccepted: false,
          callerAuthoredReceiptAccepted: false,
          boundedTimeoutMilliseconds: 120000,
          receiptBoundToCurrentTargetSnapshot: true,
        },
        sliceGate: {
          srijikaDiagnostics: 'zero',
          architecture: 'passed',
          typecheck: 'engine-executed-passed',
          productionBuild: 'engine-executed-passed',
          advanceOnlyWhenAllPass: true,
        },
        alwaysRequired: ['typecheck', 'build', 'test'],
        routeFilesPresent: {
          name: 'routes',
          routesDerivedBy: 'srijika-engine',
          browserCaptureRequired: true,
          callerAuthoredRoutesAccepted: false,
        },
        semanticRoutesPresent: {
          name: 'routes',
          routesDerivedBy: 'srijika-engine',
          concreteRouteDerivationRequired: true,
        },
        visualSourcesPresent: {
          categories: ['entry', 'component', 'style', 'asset'],
          name: 'visual',
          browserCaptureRequired: true,
          captureOwnedBy: 'srijika-engine',
          callerAuthoredEvidenceAccepted: false,
          defaultViewports: ['mobile', 'tablet', 'desktop'],
          minimumViewports: 2,
          maximumViewports: 6,
          acceptedViewports: ['mobile', 'tablet', 'desktop', 'wide'],
        },
        browserParity: {
          input: ['target', 'includeInstall?'],
          sourceRuntime: 'engine-prepared-temporary-immutable-source-copy',
          targetRuntime: 'engine-prepared-target-root',
          loopbackPortsSelectedBy: 'srijika-engine',
          routeDiscovery: 'engine-derived-from-immutable-source-session',
          evidence: ['semantic-dom-trace', 'redirects', 'console-and-page-errors', 'png'],
          thresholds: 'fixed-by-engine',
          viewports: 'fixed-by-engine',
          callerUrlsAccepted: false,
          callerViewportsAccepted: false,
          persistedManifest: '.srijika/migrations/react/browser-parity-latest.json',
          playwrightRequired: true,
        },
        finalizeRerunsGatesAndRevalidatesEngineManifest: true,
        sliceVerificationAlsoChecksSourceBaseline: true,
      },
      nativeConversion: {
        completionModes: ['native'],
        compatibilityReviewOrApplyAllowed: false,
        compatibilityMayFinalize: false,
        genericRuntimeIgnoreAllowed: false,
        zeroWriteRuntimeSliceAllowed: false,
        nonruntimeExclusionsMustBeEngineClassified: true,
        contentAddressedAssetsMayAvoidRewrite: true,
        compatibilityIsPlanningHintOnly: true,
        nativeReviewRejectsCompatibilityInput: true,
        reviewTokenBinds: [
          'plan-id',
          'slice-id',
          'source-snapshot',
          'target-snapshot',
          'canonical-payload',
          'expected-hash-target-deletions',
        ],
        applyInput: ['target', 'reviewToken'],
      },
      modelEfficiency: {
        deterministicOwnershipPlan: true,
        boundedOwnershipCorrectionBeforeMigrationOnly: true,
        ownershipCorrectionBinds: [
          'target',
          'expected-plan-id',
          'expected-source-snapshot',
          'expected-target-snapshot',
        ],
        applyDoesNotRepeatReviewedPayload: true,
        readOnlyStatusForResume: true,
        statusReturnsPendingApplyHandles: true,
        inventoryAndOwnershipPaged: true,
        inventoryOwnershipAndStatusCursorsOpaqueAndQueryBound: true,
        defaultPageSize: 50,
        maximumPageSize: 200,
        ownershipCursorCannotReplayAcrossPlanOrSlice: true,
        sliceContext: {
          freshnessBinds: [
            'expected-plan-id',
            'expected-source-snapshot',
            'expected-target-snapshot',
          ],
          defaultFilesPerPage: 8,
          maximumFilesPerPage: 32,
          defaultByteBudget: 524288,
          maximumByteBudget: 2097152,
          cursorMustKeepSameTargetAndSliceId: true,
          pageMetadata: ['package-dependency-specs', 'package-scripts', 'toolchain-facts'],
          fields: [
            'content-or-hash-only',
            'sha256',
            'category',
            'imports',
            'exports',
            'ownership',
            'canonical-target-paths',
          ],
        },
        preferredResultEnvelope: [
          'contractVersion',
          'sessionId',
          'phase',
          'summary',
          'blockers',
          'nextAction',
        ],
        allowedNextToolsByStage: {
          scaffolded: ['scan', 'plan'],
          planned: ['reviewOwnership', 'getSliceContext'],
          'context-read': ['reviewNativeSlice'],
          reviewed: ['applyReviewedSlice'],
          migrating: ['verifySlice', 'getSliceContext'],
          verifying: ['verifySession', 'finalize'],
          blocked: ['resume'],
          complete: [],
        },
      },
      claimBoundary:
        'No arbitrary automatic rewrite or guaranteed zero-loss claim. Unsupported or ambiguous behavior blocks completion; compatibility wrappers never satisfy native completion.',
    },
  },
  {
    uri: 'srijika://docs/cli-runtime',
    title: 'Srijika CLI and fast runtime',
    description:
      'Machine-readable shared CLI, VS Code, Desktop handoff, Vite, Node, and optional Bun contract.',
    value: {
      schemaVersion: 1,
      contractId: 'srijika.fast-developer-workflow',
      adapters: ['cli', 'vscode', 'desktop', 'codex-mcp'],
      engineResponsibilities: [
        'project-detection',
        'lockfile-detection',
        'runtime-selection',
        'ownership-scaffold-planning',
        'strict-shared-owner-planning',
        'incremental-architecture-validation',
        'vite-command-planning',
        'software-independent-mcp-project-context',
      ],
      runtime: {
        default: 'node',
        minimumNodeVersion: '22.13.0',
        optional: ['bun'],
        bunActivation: 'explicit-and-vite-only',
        incompatibleFallback: 'node-with-reason',
        dependencyResolutionIndependent: true,
        reactExecution: 'browser',
      },
      commands: {
        create:
          'complete CLI-first onboarding: scaffold, install, validate, VS Code setup, optional Studio handoff',
        init: 'create a pinned non-overwriting project',
        add: 'create only canonical Feature, Slot, Part, or owner capability files',
        check: 'validate the configured ownership subtree in-process',
        doctor: 'inspect runtimes, package manager, lockfile, and scripts',
        tests: 'synchronize, execute, and read fail-closed owner-test evidence',
        install: 'install exactly from the detected lockfile',
        dev: 'start the real strict-port Vite HMR application',
        build: 'run the project build script',
        studio: 'launch Desktop with --project for bounded native opening',
      },
      optionalIntegrations: {
        reactQuery: {
          default: false,
          createFlag: '--react-query',
          purpose: 'server cache, retry, invalidation, and mutation lifecycle',
          independentOfRuntime: true,
        },
      },
      safety: {
        overwrite: false,
        arbitraryOwnerFolders: false,
        arbitrarySharedFolders: false,
        runtimeChangesLockfile: false,
        bunRequired: false,
        desktopRequiredForCliOrVscode: false,
        desktopRequiredForCodeProjectMcp: false,
      },
      mcp: {
        config: '.mcp.json',
        instructions: 'AGENTS.md',
        tools: [
          'srijika_get_code_project',
          'srijika_check_code_project',
          'srijika_plan_code_structure',
          'srijika_apply_code_structure',
          'srijika_owner_tests',
          ...SRIJIKA_REACT_MIGRATION_TOOL_LIST,
        ],
        studioBridgeOptional: true,
        isolatedPluginBundle: {
          selfContained: true,
          includesTypeScriptRuntime: true,
          repositoryNodeModulesRequired: false,
          bareTypeScriptImportAllowed: false,
        },
      },
    },
  },
] as const;

export function registerSrijikaDocumentation(server: McpServer): void {
  for (const resource of SRIJIKA_DOCUMENTATION) {
    server.registerResource(
      resource.title,
      resource.uri,
      {
        title: resource.title,
        description: resource.description,
        mimeType: 'application/json',
      },
      () => ({
        contents: [
          {
            uri: resource.uri,
            mimeType: 'application/json',
            text: JSON.stringify(resource.value, null, 2),
          },
        ],
      }),
    );
  }
}
