packages:
  - apps/*
  - packages/*
allowBuilds:
  '@vscode/vsce-sign': set this to true or false
  esbuild: true
  keytar: set this to true or false
minimumReleaseAgeExclude:
  - '@types/react-dom@19.2.4'
  - '@types/react@19.2.18'
