packages:
  - apps/*
  - packages/*
linkWorkspacePackages: true
overrides:
  'fast-uri@>=3.0.0 <3.1.5': 3.1.5
  'hono@<4.12.34': 4.12.34
  'nanoid@<3.3.18': 3.3.18
allowBuilds:
  '@vscode/vsce-sign': set this to true or false
  esbuild: true
  keytar: set this to true or false
minimumReleaseAgeExclude:
  - '@types/react-dom@19.2.4'
  - '@types/react@19.2.18'
