// @generated by Srijika Studio. The desktop runtime may replace this infrastructure file.
import { createElement, StrictMode, type ComponentType, type ReactNode } from 'react';
import { createRoot, type Root } from 'react-dom/client';

const LIVE_PREVIEW_VERSION = 1;
const SELECT_MESSAGE = 'srijika:preview-select';
const SELECTED_MESSAGE = 'srijika:preview-selected-source';
const RUNTIME_STATE_MESSAGE = 'srijika:preview-runtime-state';
const HIT_TEST_MESSAGE = 'srijika:preview-hit-test';
const DROP_TARGET_MESSAGE = 'srijika:preview-drop-target';
const SOURCE_ATTRIBUTE = 'data-srijika-source';
const UI_SOURCE_PATTERN = /^src\/[A-Za-z0-9_./ -]+\.ui\.tsx$/;
const SOURCE_LOCATION_PATTERN = /^(src\/[A-Za-z0-9_./ -]+\.ui\.tsx):\d+:\d+$/;

type RuntimeState = 'loading' | 'ready' | 'error';
type RuntimeModule = Record<string, unknown>;

interface SelectedSourceMessage {
  type: typeof SELECTED_MESSAGE;
  version: 1;
  source: string | null;
  uiSource?: string | null;
}

interface HitTestMessage {
  type: typeof HIT_TEST_MESSAGE;
  version: 1;
  x: number;
  y: number;
}

const connectorModules = import.meta.glob<RuntimeModule>('../**/*.connector.tsx');
const providerModules = import.meta.glob<RuntimeModule>('../**/AppProviders.{ts,tsx}');
let runtimeHost: HTMLDivElement | null = null;
let runtimeRoot: Root | null = null;
let activeUiSource: string | null = null;
let selectionGeneration = 0;

function isSelectedSourceMessage(value: unknown): value is SelectedSourceMessage {
  if (typeof value !== 'object' || value === null) return false;
  const message = value as Partial<SelectedSourceMessage>;
  return (
    message.type === SELECTED_MESSAGE &&
    message.version === LIVE_PREVIEW_VERSION &&
    (typeof message.source === 'string' || message.source === null) &&
    (message.uiSource === undefined ||
      typeof message.uiSource === 'string' ||
      message.uiSource === null)
  );
}

function isHitTestMessage(value: unknown): value is HitTestMessage {
  if (typeof value !== 'object' || value === null) return false;
  const message = value as Partial<HitTestMessage>;
  return (
    message.type === HIT_TEST_MESSAGE &&
    message.version === LIVE_PREVIEW_VERSION &&
    typeof message.x === 'number' &&
    Number.isFinite(message.x) &&
    typeof message.y === 'number' &&
    Number.isFinite(message.y)
  );
}

function selectedUiSource(message: SelectedSourceMessage): string | null {
  if (typeof message.uiSource === 'string' && UI_SOURCE_PATTERN.test(message.uiSource)) {
    return message.uiSource;
  }
  if (typeof message.source !== 'string') return null;
  return SOURCE_LOCATION_PATTERN.exec(message.source)?.[1] ?? null;
}

function publishRuntimeState(state: RuntimeState, uiSource: string, error?: string): void {
  window.parent.postMessage(
    {
      type: RUNTIME_STATE_MESSAGE,
      version: LIVE_PREVIEW_VERSION,
      state,
      uiSource,
      ...(error ? { error } : {}),
    },
    '*',
  );
}

function connectorModuleKey(uiSource: string): string {
  return '../' + uiSource.slice('src/'.length).replace(/\.ui\.tsx$/, '.connector.tsx');
}

function connectorExportName(uiSource: string): string {
  const fileName = uiSource.split('/').at(-1) ?? '';
  return fileName.replace(/\.ui\.tsx$/, '') + 'Connector';
}

function componentExport(module: RuntimeModule, preferredName: string): ComponentType | null {
  const preferred = module[preferredName];
  if (typeof preferred === 'function') return preferred as ComponentType;
  const fallback = Object.entries(module).find(
    ([name, value]) => name.endsWith('Connector') && typeof value === 'function',
  )?.[1];
  if (typeof fallback === 'function') return fallback as ComponentType;
  return typeof module['default'] === 'function' ? (module['default'] as ComponentType) : null;
}

async function providerComponent(): Promise<ComponentType<{ children: ReactNode }> | null> {
  const providerEntry =
    Object.entries(providerModules).find(([path]) => path.endsWith('/app/AppProviders.tsx')) ??
    Object.entries(providerModules)[0];
  if (!providerEntry) return null;
  const module = await providerEntry[1]();
  const provider = module['AppProviders'] ?? module['default'];
  return typeof provider === 'function'
    ? (provider as ComponentType<{ children: ReactNode }>)
    : null;
}

function ensureRuntimeRoot(uiSource: string): Root {
  if (runtimeRoot && runtimeHost) {
    runtimeHost.setAttribute('aria-label', 'Live runtime preview for ' + uiSource);
    return runtimeRoot;
  }
  runtimeHost = document.createElement('div');
  runtimeHost.id = 'srijika-live-runtime-preview';
  runtimeHost.dataset.srijikaLiveRuntimePreview = 'true';
  runtimeHost.setAttribute('aria-label', 'Live runtime preview for ' + uiSource);
  Object.assign(runtimeHost.style, {
    position: 'fixed',
    inset: '0',
    zIndex: '2147483646',
    overflow: 'auto',
    background: 'var(--srijika-preview-background, Canvas)',
  });
  document.body.append(runtimeHost);
  runtimeRoot = createRoot(runtimeHost);
  return runtimeRoot;
}

function removeRuntimeRoot(): void {
  runtimeRoot?.unmount();
  runtimeRoot = null;
  runtimeHost?.remove();
  runtimeHost = null;
}

function runtimeErrorView(uiSource: string, message: string) {
  return createElement(
    'main',
    {
      role: 'alert',
      style: {
        minHeight: '100vh',
        padding: '32px',
        color: '#fecaca',
        background: '#190f16',
        fontFamily: 'ui-sans-serif, system-ui, sans-serif',
      },
    },
    createElement('p', null, 'Srijika live runtime error'),
    createElement('h1', null, 'Could not render ' + uiSource),
    createElement('pre', { style: { whiteSpace: 'pre-wrap' } }, message),
  );
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

async function renderSelectedConnector(uiSource: string): Promise<void> {
  const generation = ++selectionGeneration;
  if (activeUiSource === uiSource && runtimeRoot) {
    publishRuntimeState('ready', uiSource);
    return;
  }
  activeUiSource = uiSource;
  publishRuntimeState('loading', uiSource);
  const root = ensureRuntimeRoot(uiSource);
  try {
    const key = connectorModuleKey(uiSource);
    const loader = connectorModules[key];
    if (!loader) {
      throw new Error('Required Connector module was not found at ' + key.slice(3) + '.');
    }
    const [module, Provider] = await Promise.all([loader(), providerComponent()]);
    if (generation !== selectionGeneration || activeUiSource !== uiSource) return;
    const Connector = componentExport(module, connectorExportName(uiSource));
    if (!Connector) {
      throw new Error('The matching module does not export ' + connectorExportName(uiSource) + '.');
    }
    const connector = createElement(Connector);
    root.render(
      createElement(
        StrictMode,
        null,
        Provider ? createElement(Provider, null, connector) : connector,
      ),
    );
    publishRuntimeState('ready', uiSource);
  } catch (error) {
    if (generation !== selectionGeneration || activeUiSource !== uiSource) return;
    const message = errorMessage(error);
    root.render(runtimeErrorView(uiSource, message));
    publishRuntimeState('error', uiSource, message);
  }
}

function updateSelectionHighlight(source: string | null): void {
  for (const element of document.querySelectorAll<HTMLElement>('[' + SOURCE_ATTRIBUTE + ']')) {
    if (source !== null && element.getAttribute(SOURCE_ATTRIBUTE) === source) {
      element.dataset.srijikaStudioSelected = 'true';
    } else {
      delete element.dataset.srijikaStudioSelected;
    }
  }
}

function installPreviewSelectionBridge(): void {
  if (!import.meta.env.DEV || window.parent === window) return;

  const style = document.createElement('style');
  style.textContent =
    '[' +
    SOURCE_ATTRIBUTE +
    "][data-srijika-studio-selected='true'] {\n" +
    '  outline: 2px solid #7c83ff !important;\n' +
    '  outline-offset: 2px !important;\n' +
    '}';
  document.head.append(style);

  document.addEventListener(
    'pointerdown',
    (event) => {
      if (!(event.target instanceof Element)) return;
      const element = event.target.closest<HTMLElement>('[' + SOURCE_ATTRIBUTE + ']');
      const source = element?.getAttribute(SOURCE_ATTRIBUTE);
      if (!source) return;
      window.parent.postMessage(
        { type: SELECT_MESSAGE, version: LIVE_PREVIEW_VERSION, source },
        '*',
      );
    },
    true,
  );

  window.addEventListener('message', (event) => {
    if (event.source !== window.parent) return;
    if (isHitTestMessage(event.data)) {
      const element = document
        .elementFromPoint(event.data.x, event.data.y)
        ?.closest<HTMLElement>('[' + SOURCE_ATTRIBUTE + ']');
      window.parent.postMessage(
        {
          type: DROP_TARGET_MESSAGE,
          version: LIVE_PREVIEW_VERSION,
          source: element?.getAttribute(SOURCE_ATTRIBUTE) ?? null,
        },
        '*',
      );
      return;
    }
    if (!isSelectedSourceMessage(event.data)) return;
    updateSelectionHighlight(event.data.source);
    const uiSource = selectedUiSource(event.data);
    if (uiSource) {
      void renderSelectedConnector(uiSource);
    } else {
      selectionGeneration += 1;
      activeUiSource = null;
      removeRuntimeRoot();
    }
  });

  window.addEventListener('error', (event) => {
    if (activeUiSource) publishRuntimeState('error', activeUiSource, event.message);
  });
  window.addEventListener('unhandledrejection', (event) => {
    if (activeUiSource) {
      publishRuntimeState('error', activeUiSource, errorMessage(event.reason));
    }
  });
}

installPreviewSelectionBridge();
