export { checkSrijikaArchitecture, SrijikaArchitectureIndex } from './architecture.js';
export { createSrijikaDoctorReport } from './doctor.js';
export { findSrijikaProjectRoot, inspectSrijikaProject } from './project.js';
export {
  SRIJIKA_IGNORED_PROJECT_DIRECTORIES,
  SrijikaProjectFileSystem,
} from './project-filesystem.js';
export type {
  SrijikaSafeProjectFile,
  SrijikaSafeProjectWalkOptions,
  SrijikaSafeTextFile,
} from './project-filesystem.js';
export {
  formatSrijikaCommand,
  inspectSrijikaTool,
  planSrijikaProjectCommand,
  runSrijikaCommand,
  selectSrijikaRuntime,
} from './runtime.js';
export { scaffoldSrijikaStructure } from './structure.js';
export {
  collectSrijikaTestEvidence,
  inspectSrijikaTestContract,
  planSrijikaNextApp,
  planSrijikaNextTests,
  planSrijikaViteTests,
  synchronizeSrijikaNextApp,
  synchronizeSrijikaNextTests,
  synchronizeSrijikaViteTests,
  verifySrijikaOwnerTests,
} from './testing.js';
export {
  assertSrijikaUiWritesValid,
  checkSrijikaUiDiagnostics,
  formatSrijikaUiDiagnostic,
} from './ui-diagnostics.js';
export type {
  SrijikaProspectiveUiWrite,
  SrijikaUiDiagnosticCheckResult,
} from './ui-diagnostics.js';
export {
  applyReactMigrationSlice,
  attestReactMigrationParity,
  buildReactMigrationCliArguments,
  discardReactMigrationSliceReview,
  finalizeReactMigration,
  getReactMigrationStatus,
  replanPendingReactMigration,
  getReactMigrationSliceContext,
  planReactMigration,
  reviewReactMigrationSlice,
  reviewReactMigrationOwnership,
  runReactMigrationVerificationGates,
  scanReactMigrationSource,
  startReactMigration,
  synchronizeReactMigrationTestHarness,
  synchronizeReactMigrationValidator,
  verifyReactMigration,
  verifyReactMigrationSlice,
} from './react-migration.js';
export {
  captureReactMigrationBrowserParity,
  loadReactMigrationBrowserParity,
} from './react-migration-browser-parity.js';
export type {
  CaptureReactMigrationBrowserParityRequest,
  ReactMigrationBrowserDomTrace,
  ReactMigrationBrowserParityCase,
  ReactMigrationBrowserParityManifest,
  ReactMigrationBrowserSideCapture,
  ReactMigrationParityServerBinding,
  ReactMigrationParityViewport,
} from './react-migration-browser-parity.js';
export type {
  ApplyReactMigrationSliceRequest,
  AttestReactMigrationParityRequest,
  DiscardReactMigrationSliceReviewRequest,
  GetReactMigrationSliceContextRequest,
  ReviewReactMigrationSliceRequest,
  ReviewReactMigrationOwnershipRequest,
  ReactMigrationCompletionObligation,
  ReactMigrationConversionMode,
  ReactMigrationDelete,
  ReactMigrationAppliedSlice,
  ReactMigrationCliOperation,
  ReactMigrationCliRequest,
  ReactMigrationCommandStatus,
  ReactMigrationFileCategory,
  ReactMigrationIgnoredSource,
  ReactMigrationLegacyAdapterApproval,
  ReactMigrationLegacyAdapterId,
  ReactMigrationInventory,
  ReactMigrationInventoryFile,
  ReactMigrationPhase,
  ReactMigrationModuleDependency,
  ReactMigrationOwnerKind,
  ReactMigrationOwnerRole,
  ReactMigrationOwnershipOverride,
  ReactMigrationPackageDependency,
  ReactMigrationPackageDependencyScope,
  ReactMigrationSourcePackageDependency,
  ReactMigrationOwnershipDecision,
  ReactMigrationPlan,
  ReactMigrationPlanSlice,
  ReactMigrationSession,
  ReactMigrationSliceReview,
  ReactMigrationSlice,
  ReactMigrationSliceContext,
  ReactMigrationSliceContextItem,
  ReactMigrationSliceVerification,
  ReactMigrationSourceMapping,
  ReactMigrationVerification,
  ReactMigrationWrite,
  ReactMigrationToolchainFacts,
  RunReactMigrationVerificationGatesRequest,
  StartReactMigrationRequest,
  SynchronizeReactMigrationTestHarnessRequest,
  SynchronizeReactMigrationValidatorRequest,
  VerifyReactMigrationRequest,
} from './react-migration.js';
export type {
  ScaffoldSrijikaStructureRequest,
  ScaffoldSrijikaStructureResult,
  SrijikaStructureKind,
} from './structure.js';
export type {
  CollectSrijikaTestEvidenceRequest,
  CollectSrijikaTestEvidenceResult,
  InspectSrijikaTestContractRequest,
  InspectSrijikaTestContractResult,
  PlanSrijikaNextAppRequest,
  PlanSrijikaNextAppResult,
  PlanSrijikaNextTestsRequest,
  PlanSrijikaNextTestsResult,
  PlanSrijikaViteTestsRequest,
  PlanSrijikaViteTestsResult,
  SynchronizeSrijikaNextAppRequest,
  SynchronizeSrijikaNextAppResult,
  SynchronizeSrijikaNextTestsRequest,
  SynchronizeSrijikaNextTestsResult,
  SynchronizeSrijikaViteTestsRequest,
  SynchronizeSrijikaViteTestsResult,
  SrijikaTestVerificationCommand,
  SrijikaTestVerificationGate,
  SrijikaTestVerificationGateName,
  VerifySrijikaOwnerTestsRequest,
  VerifySrijikaOwnerTestsResult,
} from './testing.js';
export { planSrijikaTestVerificationCommands } from './testing.js';
export type {
  SrijikaArchitectureCheckResult,
  SrijikaCommandPlan,
  SrijikaDoctorReport,
  SrijikaJavaScriptRuntime,
  SrijikaPackageManager,
  SrijikaProjectCommandKind,
  SrijikaProjectMetadata,
  SrijikaRuntimePreference,
  SrijikaToolAvailability,
} from './types.js';
