import type { SrijikaTestContract, SrijikaTestOwner } from '@srijika/architecture-rules';
import ts from 'typescript';

export const SRIJIKA_NEXT_APP_ADAPTER_VERSION = 'srijika-next-app-v1' as const;
export const SRIJIKA_GENERATED_NEXT_ROUTE_HEADER =
  '/* Generated by Srijika. Re-run the Next route synchronizer instead of editing this file. */' as const;

export interface SrijikaNextRouteMapping {
  pathname: string;
  ownerId: string;
}

export interface SrijikaNextBoundaryDiagnostic {
  code:
    | 'SRIJIKA-NEXT-MISSING-CLIENT-DIRECTIVE'
    | 'SRIJIKA-NEXT-MIXED-SERVER-CLIENT-BOUNDARY'
    | 'SRIJIKA-NEXT-ROUTE-OWNER';
  ownerId: string;
  fileName?: string;
  message: string;
  guidance: string;
}

export interface SrijikaNextOwnerBoundary {
  ownerId: string;
  entryFile: string | null;
  kind: 'server' | 'client' | 'invalid';
  clientEvidence: readonly string[];
  serverEvidence: readonly string[];
}

export interface SrijikaNextAppFile {
  relativePath: string;
  source: string;
  mode: 'generated' | 'create-only';
}

export interface SrijikaNextAppRouterPlan {
  version: typeof SRIJIKA_NEXT_APP_ADAPTER_VERSION;
  framework: 'next-app-router';
  ready: boolean;
  appRoot: string;
  routes: readonly SrijikaNextRouteMapping[];
  boundaries: readonly SrijikaNextOwnerBoundary[];
  diagnostics: readonly SrijikaNextBoundaryDiagnostic[];
  files: readonly SrijikaNextAppFile[];
}

export interface BuildSrijikaNextAppRouterOptions {
  routes: readonly SrijikaNextRouteMapping[];
  sources: Readonly<Record<string, string>>;
  appRoot?: string;
}

function normalizedAppRoot(value: string): string {
  const normalized = value.replaceAll('\\', '/').replace(/\/$/u, '');
  if (
    !normalized ||
    normalized.startsWith('/') ||
    normalized.split('/').some((segment) => !segment || segment === '.' || segment === '..')
  ) {
    throw new Error('The Next app root must be a safe project-relative directory.');
  }
  return normalized;
}

function normalizedPathname(value: string): string {
  if (
    !value.startsWith('/') ||
    value.includes('?') ||
    value.includes('#') ||
    value.includes('\\')
  ) {
    throw new Error(`Invalid Next route pathname: ${value}`);
  }
  const normalized = value === '/' ? value : value.replace(/\/$/u, '');
  const segments = normalized === '/' ? [] : normalized.split('/').slice(1);
  const segmentPattern =
    /^(?:[a-z0-9]+(?:-[a-z0-9]+)*|\[[A-Za-z][A-Za-z0-9_]*\]|\[\.\.\.[A-Za-z][A-Za-z0-9_]*\]|\[\[\.\.\.[A-Za-z][A-Za-z0-9_]*\]\])$/u;
  if (segments.some((segment) => !segmentPattern.test(segment))) {
    throw new Error(`Invalid or unsupported Next route pathname: ${value}`);
  }
  return normalized;
}

function routeFile(appRoot: string, pathname: string): string {
  return pathname === '/' ? `${appRoot}/page.tsx` : `${appRoot}${pathname}/page.tsx`;
}

function stripSourceExtension(value: string): string {
  return value.replace(/\.(?:[cm]?[jt]sx?)$/iu, '');
}

function relativeModuleSpecifier(fromFile: string, toFile: string): string {
  const from = fromFile.split('/');
  const to = stripSourceExtension(toFile).split('/');
  from.pop();
  let shared = 0;
  while (shared < from.length && shared < to.length && from[shared] === to[shared]) shared += 1;
  const joined = [
    ...Array.from({ length: from.length - shared }, () => '..'),
    ...to.slice(shared),
  ].join('/');
  return joined.startsWith('.') ? joined : `./${joined}`;
}

function ownerEntry(owner: SrijikaTestOwner) {
  return owner.files.find(({ role }) => role === 'connector') ?? null;
}

function sourceFacts(fileName: string, source: string) {
  const parsed = ts.createSourceFile(
    fileName,
    source,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TSX,
  );
  const first = parsed.statements[0];
  const useClient = Boolean(
    first &&
    ts.isExpressionStatement(first) &&
    ts.isStringLiteral(first.expression) &&
    first.expression.text === 'use client',
  );
  const client = new Set<string>();
  const server = new Set<string>();
  if (useClient) client.add(`${fileName}:use-client`);
  const visit = (node: ts.Node): void => {
    if (ts.isImportDeclaration(node) && ts.isStringLiteral(node.moduleSpecifier)) {
      const moduleName = node.moduleSpecifier.text;
      if (moduleName === 'server-only' || moduleName === 'next/headers') {
        server.add(`${fileName}:import:${moduleName}`);
      }
      if (moduleName === 'react') {
        const bindings = node.importClause?.namedBindings;
        if (bindings && ts.isNamedImports(bindings)) {
          for (const element of bindings.elements) {
            if (/^use[A-Z0-9]/u.test(element.name.text)) {
              client.add(`${fileName}:react-hook:${element.name.text}`);
            }
          }
        }
      }
    }
    if (
      ts.isFunctionDeclaration(node) &&
      node.modifiers?.some(({ kind }) => kind === ts.SyntaxKind.ExportKeyword) &&
      node.modifiers.some(({ kind }) => kind === ts.SyntaxKind.AsyncKeyword)
    ) {
      server.add(`${fileName}:async-export`);
    }
    if (
      ts.isCallExpression(node) &&
      ts.isIdentifier(node.expression) &&
      /^use[A-Z0-9]/u.test(node.expression.text)
    ) {
      client.add(`${fileName}:hook-call:${node.expression.text}`);
    }
    if (
      ts.isIdentifier(node) &&
      ['document', 'localStorage', 'navigator', 'sessionStorage', 'window'].includes(node.text)
    ) {
      client.add(`${fileName}:browser:${node.text}`);
    }
    ts.forEachChild(node, visit);
  };
  visit(parsed);
  return { useClient, client: [...client].sort(), server: [...server].sort() };
}

function inspectBoundary(
  owner: SrijikaTestOwner,
  sources: Readonly<Record<string, string>>,
): { boundary: SrijikaNextOwnerBoundary; diagnostics: SrijikaNextBoundaryDiagnostic[] } {
  const entry = ownerEntry(owner);
  const facts = owner.files.flatMap((file) => {
    const source = sources[file.fileName];
    return source === undefined
      ? []
      : [{ fileName: file.fileName, ...sourceFacts(file.fileName, source) }];
  });
  const entryFacts = facts.find(({ fileName }) => fileName === entry?.fileName);
  const clientEvidence = [...new Set(facts.flatMap(({ client }) => client))].sort();
  const serverEvidence = [...new Set(facts.flatMap(({ server }) => server))].sort();
  const diagnostics: SrijikaNextBoundaryDiagnostic[] = [];
  if (!entry) {
    diagnostics.push({
      code: 'SRIJIKA-NEXT-ROUTE-OWNER',
      ownerId: owner.id,
      message: `${owner.id} has no Connector public gateway for a Next route.`,
      guidance: 'Route through the owner Connector; keep src/app page files thin.',
    });
  } else if (clientEvidence.length > 0 && !entryFacts?.useClient) {
    diagnostics.push({
      code: 'SRIJIKA-NEXT-MISSING-CLIENT-DIRECTIVE',
      ownerId: owner.id,
      fileName: entry.fileName,
      message: `${owner.id} uses client lifecycle or browser APIs without a client Connector boundary.`,
      guidance: `Add 'use client' to ${entry.fileName}, or move the client behavior behind a dedicated client owner.`,
    });
  }
  if (entryFacts?.useClient && serverEvidence.length > 0) {
    diagnostics.push({
      code: 'SRIJIKA-NEXT-MIXED-SERVER-CLIENT-BOUNDARY',
      ownerId: owner.id,
      fileName: entryFacts.fileName,
      message: `${owner.id} mixes client lifecycle with async or server-only behavior.`,
      guidance:
        'Keep server loading in a Server Component and pass serializable props into a client Connector.',
    });
  }
  return {
    boundary: {
      ownerId: owner.id,
      entryFile: entry?.fileName ?? null,
      kind: diagnostics.length > 0 ? 'invalid' : entryFacts?.useClient ? 'client' : 'server',
      clientEvidence,
      serverEvidence,
    },
    diagnostics,
  };
}

export function buildSrijikaNextAppRouterPlan(
  contract: SrijikaTestContract,
  options: BuildSrijikaNextAppRouterOptions,
): SrijikaNextAppRouterPlan {
  const appRoot = normalizedAppRoot(options.appRoot ?? 'src/app');
  const owners = new Map(contract.owners.map((owner) => [owner.id, owner]));
  const routes = options.routes
    .map((route) => ({ pathname: normalizedPathname(route.pathname), ownerId: route.ownerId }))
    .sort((left, right) => left.pathname.localeCompare(right.pathname));
  if (new Set(routes.map(({ pathname }) => pathname)).size !== routes.length) {
    throw new Error('Every Srijika Next route pathname must be unique.');
  }
  const selectedOwners = [...new Set(routes.map(({ ownerId }) => ownerId))].map((ownerId) => {
    const owner = owners.get(ownerId);
    if (!owner) throw new Error(`Unknown Srijika route owner: ${ownerId}`);
    return owner;
  });
  const inspected = selectedOwners.map((owner) => inspectBoundary(owner, options.sources));
  const diagnostics = inspected.flatMap(({ diagnostics: ownerDiagnostics }) => ownerDiagnostics);
  const files: SrijikaNextAppFile[] = [
    {
      relativePath: `${appRoot}/layout.tsx`,
      source: `import type { ReactNode } from 'react';\nexport default function RootLayout({ children }: { children: ReactNode }) { return <html lang="en"><body>{children}</body></html>; }\n`,
      mode: 'create-only',
    },
  ];
  for (const route of routes) {
    const owner = owners.get(route.ownerId)!;
    const entry = ownerEntry(owner);
    if (!entry) continue;
    const relativePath = routeFile(appRoot, route.pathname);
    const symbol = `${owner.name}Connector`;
    files.push({
      relativePath,
      source: `${SRIJIKA_GENERATED_NEXT_ROUTE_HEADER}\nimport { ${symbol} } from '${relativeModuleSpecifier(relativePath, entry.fileName)}';\nexport default function Page() { return <${symbol} />; }\n`,
      mode: 'generated',
    });
  }
  return {
    version: SRIJIKA_NEXT_APP_ADAPTER_VERSION,
    framework: 'next-app-router',
    ready: diagnostics.length === 0,
    appRoot,
    routes,
    boundaries: inspected.map(({ boundary }) => boundary),
    diagnostics,
    files: files.sort((left, right) => left.relativePath.localeCompare(right.relativePath)),
  };
}
