import { lstat, readFile } from 'node:fs/promises';
import { isAbsolute, relative, resolve } from 'node:path';

import { applySrijikaOwnershipCreationPlan } from './ownership-writer.js';
import {
  SRIJIKA_GENERATED_TEST_HEADER,
  type SrijikaGeneratedTestFile,
  type SrijikaViteTestAdapterPlan,
} from './testing.js';
import type { SrijikaNextTestAdapterPlan } from './next-testing.js';
import { SRIJIKA_GENERATED_NEXT_ROUTE_HEADER, type SrijikaNextAppRouterPlan } from './next-app.js';

export interface ApplySrijikaTestAdapterResult {
  root: string;
  created: readonly string[];
  updated: readonly string[];
  unchanged: readonly string[];
  preserved: readonly string[];
}

export type ApplySrijikaViteTestAdapterResult = ApplySrijikaTestAdapterResult;
export type ApplySrijikaNextTestAdapterResult = ApplySrijikaTestAdapterResult;
export type ApplySrijikaNextAppRouterResult = ApplySrijikaTestAdapterResult;

function destinationFor(root: string, relativePath: string): string {
  const normalized = relativePath.replaceAll('\\', '/');
  if (
    !normalized ||
    normalized.startsWith('/') ||
    isAbsolute(normalized) ||
    normalized.split('/').some((segment) => !segment || segment === '.' || segment === '..')
  ) {
    throw new Error(`Unsafe generated test path: ${relativePath}`);
  }
  const destination = resolve(root, ...normalized.split('/'));
  const fromRoot = relative(root, destination);
  if (!fromRoot || fromRoot.startsWith('..') || isAbsolute(fromRoot)) {
    throw new Error(`Unsafe generated test path: ${relativePath}`);
  }
  return destination;
}

function isMissingFileError(error: unknown): boolean {
  return error instanceof Error && 'code' in error && error.code === 'ENOENT';
}

function isRecognizedGeneratedFile(file: SrijikaGeneratedTestFile, source: string): boolean {
  if (source.startsWith(SRIJIKA_GENERATED_TEST_HEADER)) return true;
  if (source.startsWith(SRIJIKA_GENERATED_NEXT_ROUTE_HEADER)) return true;
  if (source.startsWith('<!-- Generated by Srijika.')) return true;
  if (file.relativePath.endsWith('/contract.generated.json')) {
    try {
      const parsed = JSON.parse(source) as unknown;
      return (
        typeof parsed === 'object' &&
        parsed !== null &&
        'version' in parsed &&
        parsed.version === 'srijika-test-contract-v1'
      );
    } catch {
      return false;
    }
  }
  return false;
}

async function applySrijikaTestAdapterPlan(
  projectRoot: string,
  plan: Pick<
    SrijikaViteTestAdapterPlan | SrijikaNextTestAdapterPlan | SrijikaNextAppRouterPlan,
    'files'
  >,
): Promise<ApplySrijikaTestAdapterResult> {
  if (!isAbsolute(projectRoot)) {
    throw new TypeError('projectRoot must be an explicit absolute path.');
  }
  const root = resolve(projectRoot);
  const rootMetadata = await lstat(root);
  if (rootMetadata.isSymbolicLink() || !rootMetadata.isDirectory()) {
    throw new Error('projectRoot must be a real directory, not a symbolic link.');
  }
  const created: SrijikaGeneratedTestFile[] = [];
  const updated: SrijikaGeneratedTestFile[] = [];
  const unchanged: string[] = [];
  const preserved: string[] = [];
  const expectedUpdateSources: Record<string, string> = {};

  for (const file of plan.files) {
    const destination = destinationFor(root, file.relativePath);
    try {
      const metadata = await lstat(destination);
      if (metadata.isSymbolicLink() || !metadata.isFile()) {
        throw new Error(`${file.relativePath} must be a regular file.`);
      }
      const current = await readFile(destination, 'utf8');
      if (current === file.source) {
        unchanged.push(file.relativePath);
      } else if (file.mode === 'create-only') {
        preserved.push(file.relativePath);
      } else if (isRecognizedGeneratedFile(file, current)) {
        updated.push(file);
        expectedUpdateSources[file.relativePath] = current;
      } else {
        throw new Error(
          `${file.relativePath} is not a recognized generated test file; Srijika will not overwrite it.`,
        );
      }
    } catch (error) {
      if (!isMissingFileError(error)) throw error;
      created.push(file);
    }
  }

  if (created.length > 0 || updated.length > 0) {
    await applySrijikaOwnershipCreationPlan(
      root,
      {
        ownerName: 'SrijikaTests',
        ownerFolder: 'tests/srijika',
        files: created,
        updates: updated,
      },
      { expectedUpdateSources },
    );
  }
  return {
    root,
    created: created.map(({ relativePath }) => relativePath),
    updated: updated.map(({ relativePath }) => relativePath),
    unchanged: unchanged.sort(),
    preserved: preserved.sort(),
  };
}

export async function applySrijikaViteTestAdapterPlan(
  projectRoot: string,
  plan: SrijikaViteTestAdapterPlan,
): Promise<ApplySrijikaViteTestAdapterResult> {
  return applySrijikaTestAdapterPlan(projectRoot, plan);
}

export async function applySrijikaNextTestAdapterPlan(
  projectRoot: string,
  plan: SrijikaNextTestAdapterPlan,
): Promise<ApplySrijikaNextTestAdapterResult> {
  return applySrijikaTestAdapterPlan(projectRoot, plan);
}

export async function applySrijikaNextAppRouterPlan(
  projectRoot: string,
  plan: SrijikaNextAppRouterPlan,
): Promise<ApplySrijikaNextAppRouterResult> {
  if (!plan.ready) {
    throw new Error('Srijika will not write Next routes while server/client diagnostics remain.');
  }
  return applySrijikaTestAdapterPlan(projectRoot, plan);
}
