import type {
  SrijikaArchitectureCapability,
  SrijikaTestContract,
  SrijikaTestOwner,
} from '@srijika/architecture-rules';

export const SRIJIKA_VITE_TEST_ADAPTER_VERSION = 'srijika-vite-tests-v1' as const;
export const SRIJIKA_GENERATED_TEST_HEADER =
  '/* Generated by Srijika. Re-run the test synchronizer instead of editing this file. */' as const;

export interface SrijikaGeneratedTestFile {
  relativePath: string;
  source: string;
  mode: 'generated' | 'create-only';
}

export interface SrijikaGeneratedTestArtifact {
  ownerId: string;
  relativePath: string;
  requirementIds: readonly string[];
}

export interface SrijikaTestPackageRequirement {
  name: string;
  version: string;
  reason: string;
}

export interface SrijikaTestEvidenceFiles {
  vitestJson: string;
  playwrightJson: string;
}

export interface SrijikaViteTestAdapterPlan {
  version: typeof SRIJIKA_VITE_TEST_ADAPTER_VERSION;
  framework: 'vite';
  contractVersion: SrijikaTestContract['version'];
  files: readonly SrijikaGeneratedTestFile[];
  artifacts: readonly SrijikaGeneratedTestArtifact[];
  uncoveredRequirementIds: readonly string[];
  scripts: Readonly<Record<string, string>>;
  devDependencies: readonly SrijikaTestPackageRequirement[];
  evidence: SrijikaTestEvidenceFiles;
}

export interface BuildSrijikaViteTestAdapterOptions {
  packageManager?: 'pnpm' | 'npm' | 'yarn' | 'bun';
  port?: number;
}

const generatedHeader = SRIJIKA_GENERATED_TEST_HEADER;

function ownerSlug(ownerId: string): string {
  return ownerId
    .replace(/[:/]+/gu, '--')
    .replace(/[^A-Za-z0-9-]+/gu, '-')
    .replace(/^-+|-+$/gu, '')
    .toLowerCase();
}

function stripSourceExtension(value: string): string {
  return value.replace(/\.(?:[cm]?[jt]sx?)$/iu, '');
}

function relativeModuleSpecifier(fromFile: string, toFile: string): string {
  const from = fromFile.replaceAll('\\', '/').split('/');
  const to = stripSourceExtension(toFile.replaceAll('\\', '/')).split('/');
  from.pop();
  let shared = 0;
  while (shared < from.length && shared < to.length && from[shared] === to[shared]) shared += 1;
  const upward = Array.from({ length: from.length - shared }, () => '..');
  const joined = [...upward, ...to.slice(shared)].join('/');
  return joined.startsWith('.') ? joined : `./${joined}`;
}

function visualEntry(owner: SrijikaTestOwner) {
  return (
    owner.files.find(({ role }) => role === 'connector') ??
    owner.files.find(({ role }) => role === 'ui')
  );
}

function visualSymbol(owner: SrijikaTestOwner): string {
  return `${owner.name}${owner.capabilities.includes('connector') ? 'Connector' : 'UI'}`;
}

function componentTest(owner: SrijikaTestOwner, relativePath: string): string {
  const entry = visualEntry(owner);
  if (!entry) throw new Error(`Visual owner ${owner.id} has no UI or Connector entry.`);
  const symbol = visualSymbol(owner);
  const sourceImport = relativeModuleSpecifier(relativePath, entry.fileName);
  return `${generatedHeader}
import { createElement, type ComponentType } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';

import { ${symbol} } from '${sourceImport}';
import { ownerFixtures } from '../owner-fixtures';

describe('${owner.id}', () => {
  it('renders its canonical visual owner boundary', () => {
    const Component = ${symbol} as ComponentType<Record<string, unknown>>;
    const markup = renderToStaticMarkup(
      createElement(
        'div',
        { 'data-srijika-test-owner': '${owner.id}' },
        createElement(Component, ownerFixtures['${owner.id}'] ?? {}),
      ),
    );
    expect(markup).toContain('data-srijika-test-owner="${owner.id}"');
  });
});
`;
}

function runtimeTest(
  owner: SrijikaTestOwner,
  runtimeFiles: readonly { fileName: string; role: SrijikaArchitectureCapability }[],
  relativePath: string,
): string {
  const imports = runtimeFiles
    .map(
      (file, index) =>
        `import * as runtime${index} from '${relativeModuleSpecifier(relativePath, file.fileName)}';`,
    )
    .join('\n');
  const assertions = runtimeFiles
    .map(
      (file, index) =>
        `    expect(Object.keys(runtime${index}).length, '${file.role}:${file.fileName}').toBeGreaterThan(0);`,
    )
    .join('\n');
  return `${generatedHeader}
import { describe, expect, it } from 'vitest';

${imports}

describe('${owner.id}', () => {
  it('loads every canonical runtime module selected for unit coverage', () => {
${assertions}
  });
});
`;
}

function browserTest(owner: SrijikaTestOwner, slug: string): string {
  return `${generatedHeader}
import AxeBuilder from '@axe-core/playwright';
import { expect, test, type Page } from '@playwright/test';

const ownerUrl = '/tests/srijika/harness/?owner=${encodeURIComponent(owner.id)}';

async function openOwner(page: Page) {
  const pageErrors: string[] = [];
  page.on('pageerror', (error) => pageErrors.push(error.message));
  await page.goto(ownerUrl);
  const boundary = page.locator('[data-srijika-test-owner="${owner.id}"]').first();
  await expect(boundary).toBeVisible();
  expect(pageErrors).toEqual([]);
  return boundary;
}

test.describe('${owner.id}', () => {
  test('renders in an isolated real-browser harness', async ({ page }) => {
    await openOwner(page);
  });

  test('@visual keeps its fixed-viewport owner boundary stable', async ({ page }) => {
    const boundary = await openOwner(page);
    await expect(boundary).toHaveScreenshot('${slug}.png');
  });

  test('@a11y has no automatically detectable WCAG A/AA violations', async ({ page }) => {
    await openOwner(page);
    const result = await new AxeBuilder({ page })
      .include('[data-srijika-test-owner="${owner.id}"]')
      .withTags(['wcag2a', 'wcag2aa'])
      .analyze();
    expect(result.violations).toEqual([]);
  });
});
`;
}

function harnessSource(owners: readonly SrijikaTestOwner[]): string {
  const visualOwners = owners.filter((owner) => visualEntry(owner));
  const imports = visualOwners
    .map((owner, index) => {
      const entry = visualEntry(owner)!;
      return `import { ${visualSymbol(owner)} as Owner${index} } from '${relativeModuleSpecifier('tests/srijika/harness/main.tsx', entry.fileName)}';`;
    })
    .join('\n');
  const entries = visualOwners
    .map(
      (owner, index) => `  '${owner.id}': Owner${index} as ComponentType<Record<string, unknown>>,`,
    )
    .join('\n');
  return `${generatedHeader}
import { createElement, type ComponentType } from 'react';
import { createRoot } from 'react-dom/client';

${imports}
import { ownerFixtures } from '../owner-fixtures';

const owners: Readonly<Record<string, ComponentType<Record<string, unknown>>>> = {
${entries}
};
const ownerId = new URLSearchParams(window.location.search).get('owner') ?? '';
const Owner = owners[ownerId];
const root = document.querySelector('#srijika-owner-root');

if (!root) throw new Error('Srijika owner harness root is missing.');
if (!Owner) throw new Error(\`Unknown Srijika owner: \${ownerId}\`);

root.setAttribute('data-srijika-test-owner', ownerId);
createRoot(root).render(createElement(Owner, ownerFixtures[ownerId] ?? {}));
`;
}

export function buildSrijikaViteTestAdapterPlan(
  contract: SrijikaTestContract,
  options: BuildSrijikaViteTestAdapterOptions = {},
): SrijikaViteTestAdapterPlan {
  const packageManager = options.packageManager ?? 'pnpm';
  const port = options.port ?? 4174;
  if (!Number.isSafeInteger(port) || port < 1_024 || port > 65_535) {
    throw new Error('The Srijika Vite test port must be an integer from 1024 through 65535.');
  }
  const files: SrijikaGeneratedTestFile[] = [];
  const artifacts: SrijikaGeneratedTestArtifact[] = [];
  const visualOwners = contract.owners.filter((owner) => owner.capabilities.includes('ui'));

  files.push(
    {
      relativePath: 'tests/srijika/contract.generated.json',
      source: `${JSON.stringify(contract, null, 2)}\n`,
      mode: 'generated',
    },
    {
      relativePath: 'tests/srijika/owner-fixtures.ts',
      source: `export const ownerFixtures: Readonly<Record<string, Record<string, unknown>>> = {};\n`,
      mode: 'create-only',
    },
    {
      relativePath: 'tests/srijika/harness/index.html',
      source: `<!-- Generated by Srijika. Re-run the test synchronizer instead of editing this file. -->\n<!doctype html>\n<html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Srijika owner harness</title></head><body><main id="srijika-owner-root"></main><script type="module" src="./main.tsx"></script></body></html>\n`,
      mode: 'generated',
    },
    {
      relativePath: 'tests/srijika/harness/main.tsx',
      source: harnessSource(visualOwners),
      mode: 'generated',
    },
    {
      relativePath: 'tests/srijika/vitest.config.ts',
      source: `${generatedHeader}\nimport { defineConfig } from 'vitest/config';\n\nexport default defineConfig({ test: { environment: 'node', include: ['tests/srijika/owners/*.test.{ts,tsx}'], reporters: ['default', 'json'], outputFile: { json: 'test-results/srijika/vitest.json' } } });\n`,
      mode: 'generated',
    },
    {
      relativePath: 'tests/srijika/playwright.config.ts',
      source: `${generatedHeader}\nimport { defineConfig, devices } from '@playwright/test';\n\nconst port = Number(process.env['SRIJIKA_OWNER_TEST_PORT'] ?? ${port});\nexport default defineConfig({\n  testDir: './owners',\n  testMatch: '**/*.spec.ts',\n  outputDir: '../../test-results/srijika/browser-artifacts',\n  fullyParallel: true,\n  reporter: [['list'], ['json', { outputFile: '../../test-results/srijika/playwright.json' }], ['html', { outputFolder: '../../playwright-report/srijika', open: 'never' }]],\n  use: { baseURL: \`http://127.0.0.1:\${port}\`, locale: 'en-US', timezoneId: 'UTC', colorScheme: 'dark', trace: 'retain-on-failure', screenshot: 'only-on-failure' },\n  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'], viewport: { width: 1440, height: 900 } } }],\n  webServer: { command: '${packageManager} dev --host 127.0.0.1 --port ' + port + ' --strictPort', url: \`http://127.0.0.1:\${port}/tests/srijika/harness/\`, reuseExistingServer: !process.env['CI'], timeout: 120_000 },\n});\n`,
      mode: 'generated',
    },
  );

  for (const owner of contract.owners) {
    const slug = ownerSlug(owner.id);
    const visualRequirements = owner.requirements
      .filter(({ layer }) => layer === 'component')
      .map(({ id }) => id);
    if (owner.capabilities.includes('ui')) {
      const componentPath = `tests/srijika/owners/${slug}.component.test.tsx`;
      files.push({
        relativePath: componentPath,
        source: componentTest(owner, componentPath),
        mode: 'generated',
      });
      artifacts.push({
        ownerId: owner.id,
        relativePath: componentPath,
        requirementIds: visualRequirements,
      });
      const browserPath = `tests/srijika/owners/${slug}.spec.ts`;
      files.push({
        relativePath: browserPath,
        source: browserTest(owner, slug),
        mode: 'generated',
      });
      artifacts.push({
        ownerId: owner.id,
        relativePath: browserPath,
        requirementIds: owner.requirements
          .filter(
            ({ layer }) => layer === 'browser' || layer === 'visual' || layer === 'accessibility',
          )
          .map(({ id }) => id),
      });
    }
    const runtimeFiles = owner.files.flatMap((file) =>
      file.role === 'store' || file.role === 'logic' || file.role === 'api'
        ? [{ fileName: file.fileName, role: file.role }]
        : [],
    );
    if (runtimeFiles.length > 0) {
      const unitPath = `tests/srijika/owners/${slug}.unit.test.ts`;
      files.push({
        relativePath: unitPath,
        source: runtimeTest(owner, runtimeFiles, unitPath),
        mode: 'generated',
      });
      artifacts.push({
        ownerId: owner.id,
        relativePath: unitPath,
        requirementIds: owner.requirements
          .filter(({ layer }) => layer === 'unit')
          .map(({ id }) => id),
      });
    }
  }

  const coveredRequirementIds = new Set([
    ...contract.owners.flatMap((owner) =>
      owner.requirements
        .filter(({ layer }) => layer === 'architecture' || layer === 'typecheck')
        .map(({ id }) => id),
    ),
    ...artifacts.flatMap(({ requirementIds }) => requirementIds),
  ]);

  return {
    version: SRIJIKA_VITE_TEST_ADAPTER_VERSION,
    framework: 'vite',
    contractVersion: contract.version,
    files: files.sort((left, right) => left.relativePath.localeCompare(right.relativePath)),
    artifacts: artifacts.sort(
      (left, right) =>
        left.ownerId.localeCompare(right.ownerId) ||
        left.relativePath.localeCompare(right.relativePath),
    ),
    uncoveredRequirementIds: contract.owners
      .flatMap((owner) => owner.requirements.map(({ id }) => id))
      .filter((id) => !coveredRequirementIds.has(id))
      .sort(),
    scripts: {
      'test:srijika': `${packageManager} run test:srijika:component && ${packageManager} run test:srijika:browser`,
      'test:srijika:component': 'vitest run --config tests/srijika/vitest.config.ts',
      'test:srijika:browser': 'playwright test --config tests/srijika/playwright.config.ts',
    },
    devDependencies: [
      {
        name: '@axe-core/playwright',
        version: '4.12.1',
        reason: 'Owner-scoped WCAG A/AA browser evidence.',
      },
      {
        name: '@playwright/test',
        version: '1.62.1',
        reason: 'Owner behavior, visual, trace, and screenshot evidence.',
      },
      { name: 'vitest', version: '4.1.10', reason: 'Owner unit and component tests.' },
    ],
    evidence: {
      vitestJson: 'test-results/srijika/vitest.json',
      playwrightJson: 'test-results/srijika/playwright.json',
    },
  };
}
